"""empty message

Revision ID: 102804b410ca
Revises: 258c7215c4ed
Create Date: 2023-08-19 16:53:33.116119

"""
from typing import Union
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "102804b410ca"
down_revision: str | None = "258c7215c4ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
