"""empty message

Revision ID: 258c7215c4ed
Revises:
Create Date: 2023-08-19 16:01:40.574074

"""
from typing import Union
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "258c7215c4ed"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
